[package]
name = "rgs"
version = "0.2.0"
authors = [
    "Artem Vorotnikov <artem@vorotnikov.me>",
]
description = "Tool for querying game servers"
repository = "https://github.com/vorot93/rgs"
keywords = [
    "game",
    "games",
]
license = "MIT"

[lib]
name = "librgs"
path = "src/lib.rs"

[[bin]]
name = "rgs"
path = "src/main.rs"

[dependencies]
byteorder = "*"
chrono = "*"
derive_more = "*"
enum-primitive-derive = "*"
env_logger = "*"
failure = "*"
failure_derive = "*"
futures = "0.1"
futures-timer = "*"
iso_country = "*"
log = "*"
nom = "*"
num-traits = "*"
openttd = { git = "https://github.com/rust-game-parsers/openttd" }
q3a = { git = "https://github.com/rust-game-parsers/q3a" }
rand = "*"
resolve = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
tokio = "*"
tokio-codec = "*"
tokio-io = "*"
tokio-dns-unofficial = "0.3.0"
tokio-ping = { git = "https://github.com/knsd/tokio-ping" }
